
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 10 10:26:40 CST 2015
//----------------------------------------------------

package net.project.parser.sequences;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INT = 11;
  public static final int EQUAL = 8;
  public static final int EOF = 0;
  public static final int INIT_SCENARIO = 4;
  public static final int ID = 10;
  public static final int END_SCENARIOS = 3;
  public static final int MORE_THAN_S = 5;
  public static final int error = 1;
  public static final int INIT_SCENARIOS = 2;
  public static final int SEMICOLON = 6;
  public static final int ORDER = 9;
  public static final int NAME = 7;
}

