/* The following code was generated by JFlex 1.4.3 on 9/16/15 11:59 PM */

package net.project.scanner.structures;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.HashMap;
import net.project.parser.structures.sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 9/16/15 11:59 PM from the specification file
 * <tt>structures.jflex</tt>
 */
public class StructuresScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\43\1\43\1\0\1\43\23\0\1\43\6\0\1\23\4\0"+
    "\1\30\2\0\1\2\12\42\1\0\1\27\1\1\1\31\1\3\2\0"+
    "\32\21\4\0\1\22\1\0\1\14\1\35\1\4\1\15\1\17\1\7"+
    "\1\11\1\26\1\10\2\21\1\37\1\34\1\6\1\5\1\24\1\40"+
    "\1\13\1\16\1\25\1\12\1\36\4\21\1\32\1\0\1\33\163\0"+
    "\1\20\u056e\0\12\41\206\0\12\41\306\0\12\41\u019c\0\12\41\166\0"+
    "\12\41\166\0\12\41\166\0\12\41\166\0\12\41\166\0\12\41\166\0"+
    "\12\41\166\0\12\41\166\0\12\41\340\0\12\41\166\0\12\41\106\0"+
    "\12\41\u0116\0\12\41\106\0\12\41\u0746\0\12\41\46\0\12\41\u012c\0"+
    "\12\41\200\0\12\41\246\0\12\41\6\0\12\41\266\0\12\41\126\0"+
    "\12\41\206\0\12\41\6\0\12\41\u89c6\0\12\41\u02a6\0\12\41\46\0"+
    "\12\41\306\0\12\41\166\0\12\41\u0196\0\12\41\u5316\0\12\41\346\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\13\1\1\2\1\3\1\4\1\5\1\6\3\1"+
    "\1\7\1\10\4\0\6\11\2\0\6\11\7\0\5\11"+
    "\2\0\7\11\10\0\2\11\1\12\3\11\2\0\1\13"+
    "\1\11\1\14\3\11\1\15\10\0\5\11\2\0\1\16"+
    "\1\17\1\20\1\11\10\0\1\21\1\22\3\11\1\0"+
    "\1\23\1\24\5\0\1\25\2\0\2\11\1\26\2\0"+
    "\1\27\3\0\1\30\1\31\1\11\1\32\1\33\1\0"+
    "\1\34\1\35\1\0\1\11\2\0\1\11\2\0\1\36"+
    "\7\0\1\37\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\374"+
    "\0\u0120\0\u0144\0\u0168\0\u018c\0\44\0\44\0\44\0\44"+
    "\0\44\0\u01b0\0\u01d4\0\u01f8\0\u021c\0\44\0\u0240\0\u0264"+
    "\0\u0288\0\u02ac\0\154\0\u02d0\0\u02f4\0\u0318\0\u033c\0\u0360"+
    "\0\u0384\0\u03a8\0\u03cc\0\u03f0\0\u0414\0\u0438\0\u045c\0\u0480"+
    "\0\u04a4\0\u04c8\0\u04ec\0\u0510\0\u0534\0\u0558\0\u057c\0\u05a0"+
    "\0\u05c4\0\u05e8\0\u060c\0\u0630\0\u0654\0\u0678\0\u069c\0\u06c0"+
    "\0\u06e4\0\u0708\0\u072c\0\u0750\0\u0774\0\u0798\0\u07bc\0\u07e0"+
    "\0\u0804\0\u0828\0\u084c\0\u0870\0\u0894\0\u08b8\0\u08dc\0\154"+
    "\0\u0900\0\u0924\0\u0948\0\u096c\0\u0990\0\154\0\u09b4\0\154"+
    "\0\u09d8\0\u09fc\0\u0a20\0\154\0\u0a44\0\u0a68\0\u0a8c\0\u0ab0"+
    "\0\u0ad4\0\u0af8\0\u0b1c\0\u0b40\0\u0b64\0\u0b88\0\u0bac\0\u0bd0"+
    "\0\u0bf4\0\u0c18\0\u0c3c\0\154\0\154\0\154\0\u0c60\0\u0c84"+
    "\0\u0ca8\0\u0ccc\0\u0cf0\0\u0d14\0\u0d38\0\u0d5c\0\u0d80\0\154"+
    "\0\154\0\u0da4\0\u0dc8\0\u0dec\0\u0e10\0\44\0\154\0\u0e34"+
    "\0\u0e58\0\u0e7c\0\u0ea0\0\u0ec4\0\44\0\u0ee8\0\u0f0c\0\u0f30"+
    "\0\u0f54\0\154\0\u0f78\0\u0f9c\0\44\0\u0fc0\0\u0fe4\0\u1008"+
    "\0\44\0\44\0\u102c\0\154\0\44\0\u1050\0\44\0\44"+
    "\0\u1074\0\u1098\0\u10bc\0\u10e0\0\u1104\0\u1128\0\u114c\0\154"+
    "\0\u1170\0\u1194\0\u11b8\0\u11dc\0\u1200\0\u1224\0\u1248\0\44"+
    "\0\44";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\2\2\4\1\5\1\4\1\6\3\4"+
    "\1\7\1\10\1\4\1\11\1\2\1\4\1\2\1\12"+
    "\1\4\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\2\4\2\25\1\26\46\0\1\27"+
    "\1\0\1\30\2\0\1\31\5\0\1\32\32\0\14\33"+
    "\1\0\2\33\1\0\3\33\5\0\5\33\1\0\1\33"+
    "\5\0\1\33\1\34\12\33\1\0\2\33\1\0\3\33"+
    "\5\0\5\33\1\0\1\33\5\0\14\33\1\0\2\33"+
    "\1\0\3\33\5\0\1\35\4\33\1\0\1\33\5\0"+
    "\7\33\1\36\4\33\1\0\2\33\1\0\3\33\5\0"+
    "\5\33\1\0\1\33\5\0\13\33\1\37\1\0\2\33"+
    "\1\0\3\33\5\0\5\33\1\0\1\33\5\0\2\33"+
    "\1\40\11\33\1\0\2\33\1\0\3\33\5\0\5\33"+
    "\1\0\1\33\17\0\1\41\5\0\1\42\23\0\4\33"+
    "\1\43\7\33\1\0\2\33\1\0\3\33\5\0\5\33"+
    "\1\0\1\33\5\0\13\33\1\44\1\0\2\33\1\0"+
    "\3\33\5\0\5\33\1\0\1\33\5\0\13\33\1\45"+
    "\1\0\2\33\1\0\3\33\5\0\5\33\1\0\1\33"+
    "\5\0\1\33\1\46\12\33\1\0\2\33\1\0\3\33"+
    "\5\0\3\33\1\47\1\33\1\0\1\33\5\0\4\33"+
    "\1\50\7\33\1\0\2\33\1\0\3\33\5\0\5\33"+
    "\1\0\1\33\42\0\2\25\5\0\1\51\2\0\1\52"+
    "\5\0\1\53\33\0\1\54\43\0\1\55\2\0\1\56"+
    "\43\0\1\57\37\0\14\33\1\0\2\33\1\0\3\33"+
    "\5\0\1\60\4\33\1\0\1\33\5\0\10\33\1\61"+
    "\3\33\1\0\2\33\1\0\3\33\5\0\5\33\1\0"+
    "\1\33\5\0\14\33\1\0\2\33\1\0\3\33\5\0"+
    "\1\62\4\33\1\0\1\33\5\0\12\33\1\63\1\33"+
    "\1\0\2\33\1\0\3\33\5\0\5\33\1\0\1\33"+
    "\5\0\13\33\1\64\1\0\2\33\1\0\3\33\5\0"+
    "\5\33\1\0\1\33\26\0\1\65\32\0\1\66\33\0"+
    "\14\33\1\0\2\33\1\0\1\67\2\33\5\0\5\33"+
    "\1\0\1\33\5\0\7\33\1\70\4\33\1\0\2\33"+
    "\1\0\3\33\5\0\5\33\1\0\1\33\5\0\14\33"+
    "\1\0\2\33\1\0\1\33\1\71\1\33\5\0\5\33"+
    "\1\0\1\33\5\0\2\33\1\72\11\33\1\0\2\33"+
    "\1\0\3\33\5\0\1\73\4\33\1\0\1\33\5\0"+
    "\1\33\1\74\12\33\1\0\2\33\1\0\3\33\5\0"+
    "\5\33\1\0\1\33\5\0\11\33\1\75\2\33\1\0"+
    "\2\33\1\0\3\33\5\0\5\33\1\0\1\33\6\0"+
    "\1\76\43\0\1\77\2\0\1\100\43\0\1\101\41\0"+
    "\1\102\43\0\1\103\46\0\1\104\50\0\1\105\31\0"+
    "\14\33\1\0\2\33\1\0\3\33\5\0\1\33\1\106"+
    "\3\33\1\0\1\33\5\0\5\33\1\107\6\33\1\0"+
    "\2\33\1\0\3\33\5\0\5\33\1\0\1\33\5\0"+
    "\10\33\1\110\3\33\1\0\2\33\1\0\3\33\5\0"+
    "\5\33\1\0\1\33\5\0\1\111\13\33\1\0\2\33"+
    "\1\0\1\33\1\112\1\33\5\0\5\33\1\0\1\33"+
    "\5\0\14\33\1\0\2\33\1\0\3\33\5\0\1\113"+
    "\4\33\1\0\1\33\14\0\1\114\55\0\1\115\22\0"+
    "\1\33\1\116\12\33\1\0\2\33\1\0\3\33\5\0"+
    "\5\33\1\0\1\33\5\0\1\33\1\117\12\33\1\0"+
    "\2\33\1\0\3\33\5\0\5\33\1\0\1\33\5\0"+
    "\10\33\1\120\3\33\1\0\2\33\1\0\3\33\5\0"+
    "\5\33\1\0\1\33\5\0\6\33\1\121\5\33\1\0"+
    "\2\33\1\0\3\33\5\0\5\33\1\0\1\33\5\0"+
    "\14\33\1\0\2\33\1\0\3\33\5\0\1\33\1\122"+
    "\3\33\1\0\1\33\5\0\14\33\1\0\2\33\1\0"+
    "\3\33\5\0\4\33\1\123\1\0\1\33\5\0\10\33"+
    "\1\124\3\33\1\0\2\33\1\0\3\33\5\0\5\33"+
    "\1\0\1\33\7\0\1\125\43\0\1\126\46\0\1\127"+
    "\50\0\1\130\34\0\1\131\51\0\1\132\40\0\1\133"+
    "\50\0\1\134\30\0\7\33\1\135\4\33\1\0\2\33"+
    "\1\0\3\33\5\0\5\33\1\0\1\33\5\0\13\33"+
    "\1\136\1\0\2\33\1\0\3\33\5\0\5\33\1\0"+
    "\1\33\5\0\7\33\1\137\4\33\1\0\2\33\1\0"+
    "\3\33\5\0\5\33\1\0\1\33\5\0\7\33\1\140"+
    "\4\33\1\0\2\33\1\0\3\33\5\0\5\33\1\0"+
    "\1\33\5\0\4\33\1\141\7\33\1\0\2\33\1\0"+
    "\3\33\5\0\5\33\1\0\1\33\11\0\1\142\61\0"+
    "\1\143\21\0\13\33\1\144\1\0\2\33\1\0\3\33"+
    "\5\0\5\33\1\0\1\33\5\0\12\33\1\145\1\33"+
    "\1\0\2\33\1\0\3\33\5\0\5\33\1\0\1\33"+
    "\5\0\10\33\1\146\3\33\1\0\2\33\1\0\3\33"+
    "\5\0\5\33\1\0\1\33\5\0\6\33\1\147\5\33"+
    "\1\0\2\33\1\0\3\33\5\0\5\33\1\0\1\33"+
    "\10\0\1\150\51\0\1\151\40\0\1\152\50\0\1\153"+
    "\34\0\1\154\40\0\1\155\51\0\1\156\50\0\1\157"+
    "\27\0\13\33\1\160\1\0\2\33\1\0\3\33\5\0"+
    "\5\33\1\0\1\33\5\0\2\33\1\161\11\33\1\0"+
    "\2\33\1\0\3\33\5\0\5\33\1\0\1\33\5\0"+
    "\4\33\1\162\7\33\1\0\2\33\1\0\3\33\5\0"+
    "\5\33\1\0\1\33\5\0\6\33\1\163\5\33\1\0"+
    "\2\33\1\0\3\33\5\0\5\33\1\0\1\33\5\0"+
    "\5\33\1\164\6\33\1\0\2\33\1\0\3\33\5\0"+
    "\5\33\1\0\1\33\7\0\1\165\60\0\1\166\24\0"+
    "\13\33\1\167\1\0\2\33\1\0\3\33\5\0\5\33"+
    "\1\0\1\33\11\0\1\170\40\0\1\171\51\0\1\172"+
    "\50\0\1\173\34\0\1\174\35\0\1\175\54\0\1\176"+
    "\34\0\1\177\42\0\14\33\1\0\2\33\1\0\1\200"+
    "\2\33\5\0\5\33\1\0\1\33\5\0\4\33\1\201"+
    "\7\33\1\0\2\33\1\0\3\33\5\0\5\33\1\0"+
    "\1\33\5\0\1\33\1\202\12\33\1\0\2\33\1\0"+
    "\3\33\5\0\5\33\1\0\1\33\12\0\1\203\43\0"+
    "\1\204\35\0\1\205\54\0\1\206\34\0\1\207\50\0"+
    "\1\210\34\0\1\211\43\0\1\212\44\0\1\213\13\33"+
    "\1\0\2\33\1\0\3\33\5\0\5\33\1\0\1\33"+
    "\5\0\7\33\1\214\4\33\1\0\2\33\1\0\3\33"+
    "\5\0\5\33\1\0\1\33\24\0\1\215\32\0\1\216"+
    "\34\0\1\217\43\0\1\220\53\0\1\221\34\0\4\33"+
    "\1\222\7\33\1\0\2\33\1\0\3\33\5\0\5\33"+
    "\1\0\1\33\14\0\1\223\44\0\1\224\33\0\1\33"+
    "\1\225\12\33\1\0\2\33\1\0\3\33\5\0\5\33"+
    "\1\0\1\33\15\0\1\226\33\0\1\227\43\0\2\33"+
    "\1\230\11\33\1\0\2\33\1\0\3\33\5\0\5\33"+
    "\1\0\1\33\5\0\1\231\47\0\1\232\43\0\1\233"+
    "\40\0\1\234\43\0\1\235\44\0\1\236\43\0\1\237"+
    "\40\0\1\240\43\0\1\241\40\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4716];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\12\1\5\11\4\1\1\11\4\0\6\1"+
    "\2\0\6\1\7\0\5\1\2\0\7\1\10\0\6\1"+
    "\2\0\7\1\10\0\5\1\2\0\4\1\10\0\5\1"+
    "\1\0\1\11\1\1\5\0\1\11\2\0\3\1\2\0"+
    "\1\11\3\0\2\11\2\1\1\11\1\0\2\11\1\0"+
    "\1\1\2\0\1\1\2\0\1\1\7\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public ArrayList<HashMap<String, String>> errors = new ArrayList<>();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn);
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public StructuresScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public StructuresScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 240) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { return symbol(sym.END_BG);
          }
        case 33: break;
        case 22: 
          { return symbol(sym.ENEMY);
          }
        case 34: break;
        case 2: 
          { return symbol(sym.SEMICOLON);
          }
        case 35: break;
        case 24: 
          { return symbol(sym.INIT_FIGURE);
          }
        case 36: break;
        case 18: 
          { return symbol(sym.PICTURE);
          }
        case 37: break;
        case 30: 
          { return symbol(sym.DESCRIPTION);
          }
        case 38: break;
        case 15: 
          { return symbol(sym.BONUS);
          }
        case 39: break;
        case 10: 
          { return symbol(sym.WEAPON);
          }
        case 40: break;
        case 16: 
          { return symbol(sym.BOMB);
          }
        case 41: break;
        case 9: 
          { return symbol(sym.ID);
          }
        case 42: break;
        case 1: 
          { System.out.println("Line: " + (yyline + 1) + ", column: " + (yycolumn + 1) + ", Lexical error in: " + yytext());
    HashMap<String, String> error = new HashMap<>();
    error.put("line", Integer.toString(yyline + 1));
    error.put("column", Integer.toString(yycolumn +1));
    error.put("text", yytext());
    error.put("number", Integer.toString(errors.size() + 1));
    errors.add( error );
          }
        case 43: break;
        case 4: 
          { return symbol(sym.EQUAL);
          }
        case 44: break;
        case 20: 
          { return symbol(sym.BLOCK);
          }
        case 45: break;
        case 25: 
          { return symbol(sym.INIT_DESIGN);
          }
        case 46: break;
        case 3: 
          { return symbol(sym.COMMA);
          }
        case 47: break;
        case 5: 
          { return symbol(sym.O_BRACE);
          }
        case 48: break;
        case 28: 
          { return symbol(sym.END_FIGURE);
          }
        case 49: break;
        case 31: 
          { return symbol(sym.INIT_CONF);
          }
        case 50: break;
        case 8: 
          { /* white space */
          }
        case 51: break;
        case 32: 
          { return symbol(sym.END_CONF);
          }
        case 52: break;
        case 27: 
          { return symbol(sym.STRING);
          }
        case 53: break;
        case 12: 
          { return symbol(sym.FINISH);
          }
        case 54: break;
        case 29: 
          { return symbol(sym.END_DESIGN);
          }
        case 55: break;
        case 26: 
          { return symbol(sym.DESTROY);
          }
        case 56: break;
        case 6: 
          { return symbol(sym.C_BRACE);
          }
        case 57: break;
        case 19: 
          { return symbol(sym.PATH);
          }
        case 58: break;
        case 14: 
          { return symbol(sym.HERO);
          }
        case 59: break;
        case 17: 
          { return symbol(sym.NAME);
          }
        case 60: break;
        case 7: 
          { return symbol(sym.INT);
          }
        case 61: break;
        case 13: 
          { return symbol(sym.LIVE);
          }
        case 62: break;
        case 11: 
          { return symbol(sym.TYPE);
          }
        case 63: break;
        case 21: 
          { return symbol(sym.INIT_BG);
          }
        case 64: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
