
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 05 05:03:52 CST 2015
//----------------------------------------------------

package net.project.parser.structures;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.HashMap;
import net.project.utils.GenericAttr;
import net.project.utils.GenericElement;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Oct 05 05:03:52 CST 2015
  */
public class StructuresParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public StructuresParser() {super();}

  /** Constructor which sets the default scanner. */
  public StructuresParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public StructuresParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\002\005\000\002\002" +
    "\003\000\002\003\003\000\002\003\004\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\005\005\000" +
    "\002\006\003\000\002\006\005\000\002\007\005\000\002" +
    "\027\004\000\002\027\005\000\002\024\003\000\002\024" +
    "\003\000\002\010\005\000\002\011\003\000\002\011\005" +
    "\000\002\012\005\000\002\030\004\000\002\030\005\000" +
    "\002\025\003\000\002\025\003\000\002\025\003\000\002" +
    "\025\003\000\002\025\003\000\002\025\003\000\002\032" +
    "\004\000\002\032\004\000\002\013\005\000\002\014\005" +
    "\000\002\015\005\000\002\016\005\000\002\017\003\000" +
    "\002\017\005\000\002\020\005\000\002\031\004\000\002" +
    "\031\005\000\002\026\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\021\004\000\002\021\004" +
    "\000\002\021\004\000\002\021\004\000\002\021\004\000" +
    "\002\022\005\000\002\033\005\000\002\034\005\000\002" +
    "\023\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\131\000\006\003\004\004\006\001\002\000\004\002" +
    "\uffff\001\002\000\004\002\133\001\002\000\010\006\014" +
    "\010\013\012\016\001\002\000\012\005\ufffb\006\ufffb\010" +
    "\ufffb\012\ufffb\001\002\000\012\005\ufffa\006\ufffa\010\ufffa" +
    "\012\ufffa\001\002\000\004\005\132\001\002\000\012\005" +
    "\ufffc\006\ufffc\010\ufffc\012\ufffc\001\002\000\004\014\076" +
    "\001\002\000\004\014\061\001\002\000\012\005\ufffe\006" +
    "\014\010\013\012\016\001\002\000\004\014\020\001\002" +
    "\000\006\013\uffdf\016\055\001\002\000\012\021\035\022" +
    "\023\023\031\025\030\001\002\000\004\013\022\001\002" +
    "\000\012\005\uffe0\006\uffe0\010\uffe0\012\uffe0\001\002\000" +
    "\004\017\053\001\002\000\004\020\uffda\001\002\000\004" +
    "\020\051\001\002\000\004\020\uffd8\001\002\000\004\020" +
    "\uffd9\001\002\000\004\017\047\001\002\000\004\017\046" +
    "\001\002\000\014\032\041\033\044\034\045\035\042\036" +
    "\043\001\002\000\004\015\040\001\002\000\004\020\uffd7" +
    "\001\002\000\004\017\036\001\002\000\004\037\037\001" +
    "\002\000\004\020\uffd0\001\002\000\006\013\uffdd\016\uffdd" +
    "\001\002\000\004\020\uffd6\001\002\000\004\020\uffd3\001" +
    "\002\000\004\020\uffd2\001\002\000\004\020\uffd5\001\002" +
    "\000\004\020\uffd4\001\002\000\020\030\uffce\031\uffce\032" +
    "\uffce\033\uffce\034\uffce\035\uffce\036\uffce\001\002\000\004" +
    "\027\050\001\002\000\004\020\uffd1\001\002\000\014\015" +
    "\uffdc\021\035\022\023\023\031\025\030\001\002\000\004" +
    "\015\uffdb\001\002\000\004\040\054\001\002\000\004\020" +
    "\uffcf\001\002\000\004\014\020\001\002\000\004\013\uffde" +
    "\001\002\000\004\005\ufffd\001\002\000\004\007\074\001" +
    "\002\000\006\021\035\022\023\001\002\000\006\007\ufff8" +
    "\016\063\001\002\000\004\014\061\001\002\000\004\007" +
    "\ufff7\001\002\000\004\020\ufff3\001\002\000\004\020\ufff2" +
    "\001\002\000\004\020\072\001\002\000\004\015\071\001" +
    "\002\000\006\007\ufff6\016\ufff6\001\002\000\010\015\ufff5" +
    "\021\035\022\023\001\002\000\004\015\ufff4\001\002\000" +
    "\012\005\ufff9\006\ufff9\010\ufff9\012\ufff9\001\002\000\006" +
    "\011\ufff0\016\130\001\002\000\016\021\035\022\023\023" +
    "\031\024\103\025\107\026\106\001\002\000\004\011\100" +
    "\001\002\000\012\005\ufff1\006\ufff1\010\ufff1\012\ufff1\001" +
    "\002\000\004\020\126\001\002\000\004\020\uffeb\001\002" +
    "\000\004\017\124\001\002\000\004\020\uffe9\001\002\000" +
    "\004\020\uffea\001\002\000\004\017\122\001\002\000\004" +
    "\017\120\001\002\000\004\020\uffe6\001\002\000\004\020" +
    "\uffe8\001\002\000\006\030\117\031\116\001\002\000\004" +
    "\015\115\001\002\000\004\020\uffe7\001\002\000\006\011" +
    "\uffee\016\uffee\001\002\000\004\020\uffe4\001\002\000\004" +
    "\020\uffe5\001\002\000\004\027\121\001\002\000\004\020" +
    "\uffe2\001\002\000\004\041\123\001\002\000\004\020\uffe1" +
    "\001\002\000\004\027\125\001\002\000\004\020\uffe3\001" +
    "\002\000\020\015\uffed\021\035\022\023\023\031\024\103" +
    "\025\107\026\106\001\002\000\004\015\uffec\001\002\000" +
    "\004\014\076\001\002\000\004\011\uffef\001\002\000\004" +
    "\002\000\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\131\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\003\010\004\014\005\011\010\006" +
    "\016\007\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\011\076\012\074" +
    "\001\001\000\006\006\057\007\061\001\001\000\014\003" +
    "\056\004\014\005\011\010\006\016\007\001\001\000\006" +
    "\017\020\020\016\001\001\000\002\001\001\000\020\021" +
    "\025\022\033\023\031\026\024\031\032\033\023\034\026" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\021\025\022\033" +
    "\023\031\026\024\031\051\033\023\034\026\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\017\055\020\016\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\024\066\027\067\033\064" +
    "\034\065\001\001\000\002\001\001\000\006\006\063\007" +
    "\061\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\024\066\027\072\033\064\034\065\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\024\013\110\014\113\015\107\023\111\025\100\030\112" +
    "\032\103\033\101\034\104\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\024\013\110" +
    "\014\113\015\107\023\111\025\100\030\126\032\103\033" +
    "\101\034\104\001\001\000\002\001\001\000\006\011\130" +
    "\012\074\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$StructuresParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$StructuresParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$StructuresParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public boolean hasUnRecoveredSyntaxError = false;
    public ArrayList<HashMap<String, String>> errors = new ArrayList<>();
    public ArrayList<GenericElement> bgs = new ArrayList<>();
    public ArrayList<GenericElement> figures = new ArrayList<>();
    public ArrayList<GenericElement> designs = new ArrayList<>();

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        // has some un-recovered syntax error(structure error)
        this.hasUnRecoveredSyntaxError = true;
    }

    public void syntax_error(Symbol cur_token) {
        HashMap<String, String> error = new HashMap<>();
        error.put("text", (String) cur_token.value);
        // todo add token type
        error.put("number", Integer.toString(errors.size() + 1));
        errors.add( error );
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$StructuresParser$actions {
  private final StructuresParser parser;

  /** Constructor */
  CUP$StructuresParser$actions(StructuresParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$StructuresParser$do_action(
    int                        CUP$StructuresParser$act_num,
    java_cup.runtime.lr_parser CUP$StructuresParser$parser,
    java.util.Stack            CUP$StructuresParser$stack,
    int                        CUP$StructuresParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$StructuresParser$result;

      /* select the action based on the action number */
      switch (CUP$StructuresParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // generic_type ::= TYPE EQUAL 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("generic_type",17, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // picture ::= PICTURE EQUAL PATH 
            {
              String RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
    RESULT = path;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("picture",26, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // name ::= NAME EQUAL ID 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
    RESULT = id;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("name",25, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // design_destroy ::= DESTROY EQUAL INT 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		 RESULT = i; 
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_destroy",16, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // design_type ::= generic_type WEAPON 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		 RESULT = t; 
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_type",15, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // design_type ::= generic_type BOMB 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		 RESULT = t; 
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_type",15, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // design_type ::= generic_type BONUS 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		 RESULT = t; 
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_type",15, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // design_type ::= generic_type BLOCK 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		 RESULT = t; 
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_type",15, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // design_type ::= generic_type FINISH 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		 RESULT = t; 
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_type",15, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // design_attr ::= design_destroy 
            {
              GenericAttr RESULT =null;
		int destroyleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int destroyright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		Object destroy = (Object)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<Integer>();
                    RESULT.setType("destroy");
                    RESULT.setValue(destroy);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_attr",20, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // design_attr ::= design_type 
            {
              GenericAttr RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<String>();
                    RESULT.setType("type");
                    RESULT.setValue(type);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_attr",20, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // design_attr ::= picture 
            {
              GenericAttr RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<String>();
                    RESULT.setType("picture");
                    RESULT.setValue(p);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_attr",20, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // design_attr ::= name 
            {
              GenericAttr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<String>();
                    RESULT.setType("name");
                    RESULT.setValue(n);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_attr",20, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // design_attrs ::= design_attr SEMICOLON design_attrs 
            {
              GenericElement RESULT =null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)).right;
		GenericAttr attr = (GenericAttr)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)).value;
		int attrsleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int attrsright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		GenericElement attrs = (GenericElement)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericElement();
                    RESULT.addAttr(attr);
                    RESULT.addAll(attrs);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_attrs",23, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // design_attrs ::= design_attr SEMICOLON 
            {
              GenericElement RESULT =null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).right;
		GenericAttr attr = (GenericAttr)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).value;
		
                    RESULT = new GenericElement();
                    RESULT.addAttr(attr);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_attrs",23, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // design_element ::= O_BRACE design_attrs C_BRACE 
            {
              Object RESULT =null;
		int designleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).left;
		int designright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).right;
		GenericElement design = (GenericElement)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).value;
		
                    this.parser.designs.add(design);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_element",14, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // design_elements ::= design_element COMMA design_elements 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_elements",13, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // design_elements ::= design_element 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design_elements",13, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // design ::= INIT_DESIGN design_elements END_DESIGN 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("design",12, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // figure_description ::= DESCRIPTION EQUAL STRING 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		 RESULT = s; 
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_description",11, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // figure_destroy ::= DESTROY EQUAL INT 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		 RESULT = i; 
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_destroy",10, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // figure_live ::= LIVE EQUAL INT 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		 RESULT = i; 
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_live",9, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // figure_type ::= generic_type ENEMY 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = e;
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_type",24, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // figure_type ::= generic_type HERO 
            {
              String RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int hright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = h;
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_type",24, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // figure_attr ::= figure_description 
            {
              GenericAttr RESULT =null;
		int descriptionleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int descriptionright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		Object description = (Object)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<String>();
                    RESULT.setType("description");
                    RESULT.setValue(description);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_attr",19, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // figure_attr ::= figure_destroy 
            {
              GenericAttr RESULT =null;
		int destroyleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int destroyright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		Object destroy = (Object)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<Integer>();
                    RESULT.setType("destroy");
                    RESULT.setValue(destroy);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_attr",19, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // figure_attr ::= figure_live 
            {
              GenericAttr RESULT =null;
		int liveleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int liveright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		Object live = (Object)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<Integer>();
                    RESULT.setType("live");
                    RESULT.setValue(live);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_attr",19, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // figure_attr ::= figure_type 
            {
              GenericAttr RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<String>();
                    RESULT.setType("type");
                    RESULT.setValue(type);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_attr",19, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // figure_attr ::= picture 
            {
              GenericAttr RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<String>();
                    RESULT.setType("picture");
                    RESULT.setValue(p);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_attr",19, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // figure_attr ::= name 
            {
              GenericAttr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericAttr<String>();
                    RESULT.setType("name");
                    RESULT.setValue(n);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_attr",19, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // figure_attrs ::= figure_attr SEMICOLON figure_attrs 
            {
              GenericElement RESULT =null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)).right;
		GenericAttr attr = (GenericAttr)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)).value;
		int attrsleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int attrsright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		GenericElement attrs = (GenericElement)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                    RESULT = new GenericElement();
                    RESULT.addAttr(attr);
                    RESULT.addAll(attrs);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_attrs",22, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // figure_attrs ::= figure_attr SEMICOLON 
            {
              GenericElement RESULT =null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).right;
		GenericAttr attr = (GenericAttr)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).value;
		
                    RESULT = new GenericElement();
                    RESULT.addAttr(attr);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_attrs",22, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // figure_element ::= O_BRACE figure_attrs C_BRACE 
            {
              Object RESULT =null;
		int figureleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).left;
		int figureright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).right;
		GenericElement figure = (GenericElement)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).value;
		
                    this.parser.figures.add(figure);
                
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_element",8, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // figure_elements ::= figure_element COMMA figure_elements 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_elements",7, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // figure_elements ::= figure_element 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure_elements",7, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // figure ::= INIT_FIGURE figure_elements END_FIGURE 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("figure",6, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // bg_attr ::= picture 
            {
              GenericAttr RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                RESULT = new GenericAttr<String>();
                RESULT.setType("picture");
                RESULT.setValue(p);
            
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("bg_attr",18, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // bg_attr ::= name 
            {
              GenericAttr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                RESULT = new GenericAttr<String>();
                RESULT.setType("name");
                RESULT.setValue(n);
            
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("bg_attr",18, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // bg_attrs ::= bg_attr SEMICOLON bg_attrs 
            {
              GenericElement RESULT =null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)).right;
		GenericAttr attr = (GenericAttr)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)).value;
		int attrsleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).left;
		int attrsright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()).right;
		GenericElement attrs = (GenericElement)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.peek()).value;
		
                RESULT = new GenericElement();
                RESULT.addAttr(attr);
                RESULT.addAll(attrs);
            
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("bg_attrs",21, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // bg_attrs ::= bg_attr SEMICOLON 
            {
              GenericElement RESULT =null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).right;
		GenericAttr attr = (GenericAttr)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).value;
		
                RESULT = new GenericElement();
                RESULT.addAttr(attr);
            
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("bg_attrs",21, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bg_element ::= O_BRACE bg_attrs C_BRACE 
            {
              Object RESULT =null;
		int bgleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).left;
		int bgright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).right;
		GenericElement bg = (GenericElement)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).value;
		
    // background element found.
    this.parser.bgs.add(bg);

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("bg_element",5, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // bg_elements ::= bg_element COMMA bg_elements 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("bg_elements",4, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // bg_elements ::= bg_element 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("bg_elements",4, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // bg ::= INIT_BG bg_elements END_BG 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("bg",3, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // element_conf ::= design 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("element_conf",2, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // element_conf ::= figure 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("element_conf",2, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // element_conf ::= bg 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("element_conf",2, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // elements_conf ::= element_conf elements_conf 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("elements_conf",1, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // elements_conf ::= element_conf 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("elements_conf",1, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // structures ::= error 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("structures",0, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // structures ::= INIT_CONF elements_conf END_CONF 
            {
              Object RESULT =null;

              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("structures",0, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-2)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          return CUP$StructuresParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= structures EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)).value;
		RESULT = start_val;
              CUP$StructuresParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.elementAt(CUP$StructuresParser$top-1)), ((java_cup.runtime.Symbol)CUP$StructuresParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$StructuresParser$parser.done_parsing();
          return CUP$StructuresParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

