
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 17 02:05:13 CST 2015
//----------------------------------------------------

package net.project.parser.structures;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int C_BRACE = 11;
  public static final int END_FIGURE = 7;
  public static final int SEMICOLON = 14;
  public static final int HERO = 22;
  public static final int INT = 21;
  public static final int EQUAL = 13;
  public static final int INIT_FIGURE = 6;
  public static final int WEAPON = 28;
  public static final int NAME = 15;
  public static final int BOMB = 27;
  public static final int INIT_CONF = 2;
  public static final int ID = 29;
  public static final int END_CONF = 3;
  public static final int PICTURE = 16;
  public static final int STRING = 31;
  public static final int DESCRIPTION = 20;
  public static final int LIVE = 18;
  public static final int TYPE = 17;
  public static final int COMMA = 12;
  public static final int END_DESIGN = 9;
  public static final int EOF = 0;
  public static final int END_BG = 5;
  public static final int ENEMY = 23;
  public static final int INIT_DESIGN = 8;
  public static final int FINISH = 24;
  public static final int error = 1;
  public static final int O_BRACE = 10;
  public static final int INIT_BG = 4;
  public static final int BONUS = 26;
  public static final int PATH = 30;
  public static final int BLOCK = 25;
  public static final int DESTROY = 19;
}

