
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package net.project.parser.structures;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int C_BRACE = 11;
  public static final int CREDITS = 20;
  public static final int END_FIGURE = 7;
  public static final int SEMICOLON = 14;
  public static final int HERO = 23;
  public static final int INT = 22;
  public static final int EQUAL = 13;
  public static final int INIT_FIGURE = 6;
  public static final int WEAPON = 29;
  public static final int NAME = 15;
  public static final int BOMB = 28;
  public static final int INIT_CONF = 2;
  public static final int ID = 30;
  public static final int END_CONF = 3;
  public static final int PICTURE = 16;
  public static final int STRING = 32;
  public static final int DESCRIPTION = 21;
  public static final int LIVE = 18;
  public static final int TYPE = 17;
  public static final int COMMA = 12;
  public static final int END_DESIGN = 9;
  public static final int EOF = 0;
  public static final int END_BG = 5;
  public static final int ENEMY = 24;
  public static final int INIT_DESIGN = 8;
  public static final int FINISH = 25;
  public static final int error = 1;
  public static final int O_BRACE = 10;
  public static final int INIT_BG = 4;
  public static final int BONUS = 27;
  public static final int PATH = 31;
  public static final int BLOCK = 26;
  public static final int DESTROY = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INIT_CONF",
  "END_CONF",
  "INIT_BG",
  "END_BG",
  "INIT_FIGURE",
  "END_FIGURE",
  "INIT_DESIGN",
  "END_DESIGN",
  "O_BRACE",
  "C_BRACE",
  "COMMA",
  "EQUAL",
  "SEMICOLON",
  "NAME",
  "PICTURE",
  "TYPE",
  "LIVE",
  "DESTROY",
  "CREDITS",
  "DESCRIPTION",
  "INT",
  "HERO",
  "ENEMY",
  "FINISH",
  "BLOCK",
  "BONUS",
  "BOMB",
  "WEAPON",
  "ID",
  "PATH",
  "STRING"
  };
}

