
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 08 22:32:49 CST 2015
//----------------------------------------------------

package net.project.parser.scenarios;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int C_PAREN = 23;
  public static final int INIT_VILLAINS = 8;
  public static final int SEMICOLON = 27;
  public static final int INT = 34;
  public static final int END_BONUS = 19;
  public static final int EQUAL = 26;
  public static final int WIDTH = 32;
  public static final int NAME = 29;
  public static final int MORE_THAN = 28;
  public static final int END_EXTRAS = 15;
  public static final int INIT_FLOOR = 12;
  public static final int ID = 33;
  public static final int INIT_CHARACTERS = 4;
  public static final int END_HEROES = 7;
  public static final int INIT_EXTRAS = 14;
  public static final int COMMA = 24;
  public static final int INIT_WALLS = 10;
  public static final int END_SCENARIO = 3;
  public static final int EOF = 0;
  public static final int INIT_HEROES = 6;
  public static final int HEIGHT = 31;
  public static final int INIT_SCENARIO = 2;
  public static final int END_FLOOR = 13;
  public static final int DOT = 25;
  public static final int error = 1;
  public static final int O_PAREN = 22;
  public static final int END_FINISH = 21;
  public static final int INIT_BONUS = 18;
  public static final int END_WALLS = 11;
  public static final int INIT_WEAPONS = 16;
  public static final int END_CHARACTERS = 5;
  public static final int INIT_FINISH = 20;
  public static final int END_WEAPONS = 17;
  public static final int BG = 30;
  public static final int END_VILLAINS = 9;
}

